const cars = [
    {
        id: '1',
        name: 'Swift',
        company: 'Maruti Suzuki',
        catagory: 'Hatchback',
        images: ['https://images.news18.com/ibnlive/uploads/2017/02/news18144.jpg',
        'https://imgd.aeplcdn.com/1200x900/n/cw/ec/54399/exterior-right-front-three-quarter-10.jpeg?q=75',
        ],
        transmission: {
            mode: 'manual',
        },
        capacity: '5',
        tankCapacity: 37.0,
        average: '22',
        fuel: 'Petrol',
        price: '500',
        availability: 'true',
        owner: 'PradipRaj Vala',
    },{
        id: '1',
        name: 'Swift',
        company: 'Maruti Suzuki',
        catagory: 'Hatchback',
        images: ['https://images.news18.com/ibnlive/uploads/2017/02/news18144.jpg',
        'https://imgd.aeplcdn.com/1200x900/n/cw/ec/54399/exterior-right-front-three-quarter-10.jpeg?q=75',
        ],
        transmission: {
            mode: 'manual',
        },
        capacity: '5',
        tankCapacity: 37.0,
        average: '22',
        fuel: 'Petrol',
        price: '500',
        availability: 'true',
        owner: 'PradipRaj Vala',
    }
    ,{
        id: '1',
        name: 'Swift',
        company: 'Maruti Suzuki',
        catagory: 'Hatchback',
        images: ['https://images.news18.com/ibnlive/uploads/2017/02/news18144.jpg',
        'https://imgd.aeplcdn.com/1200x900/n/cw/ec/54399/exterior-right-front-three-quarter-10.jpeg?q=75',
        ],
        transmission: {
            mode: 'manual',
        },
        capacity: '5',
        tankCapacity: 37.0,
        average: '22',
        fuel: 'Petrol',
        price: '500',
        availability: 'true',
        owner: 'PradipRaj Vala',
    },{
        id: '1',
        name: 'Swift',
        company: 'Maruti Suzuki',
        catagory: 'Hatchback',
        images: ['https://images.news18.com/ibnlive/uploads/2017/02/news18144.jpg',
        'https://imgd.aeplcdn.com/1200x900/n/cw/ec/54399/exterior-right-front-three-quarter-10.jpeg?q=75',
        ],
        transmission: {
            mode: 'manual',
            number: 5,
        },
        capacity: '5',
        tankCapacity: 37.0,
        average: '22',
        fuel: 'Petrol',
        price: '500',
        availability: 'true',
        owner: 'PradipRaj Vala',
    },{
        id: '1',
        name: 'Swift',
        company: 'Maruti Suzuki',
        catagory: 'Hatchback',
        images: ['https://images.news18.com/ibnlive/uploads/2017/02/news18144.jpg',
        'https://imgd.aeplcdn.com/1200x900/n/cw/ec/54399/exterior-right-front-three-quarter-10.jpeg?q=75',
        ],
        transmission: {
            mode: 'manual',
            number: 5,
        },
        capacity: '5',
        tankCapacity: 37.0,
        average: '22',
        fuel: 'Petrol',
        price: '500',
        availability: 'true',
        owner: 'PradipRaj Vala',
    },{
        id: '1',
        name: 'Swift',
        company: 'Maruti Suzuki',
        catagory: 'Hatchback',
        images: ['https://images.news18.com/ibnlive/uploads/2017/02/news18144.jpg',
        'https://imgd.aeplcdn.com/1200x900/n/cw/ec/54399/exterior-right-front-three-quarter-10.jpeg?q=75',
        ],
        transmission: {
            mode: 'manual',
            number: 5,
        },
        capacity: '5',
        tankCapacity: 37.0,
        average: '22',
        fuel: 'Petrol',
        price: '500',
        availability: 'true',
        owner: 'PradipRaj Vala',
    },{
        id: '1',
        name: 'Swift',
        company: 'Maruti Suzuki',
        catagory: 'Hatchback',
        images: ['https://images.news18.com/ibnlive/uploads/2017/02/news18144.jpg',
        'https://imgd.aeplcdn.com/1200x900/n/cw/ec/54399/exterior-right-front-three-quarter-10.jpeg?q=75',
        ],
        transmission: {
            mode: 'manual',
            number: 5,
        },
        capacity: '5',
        tankCapacity: 37.0,
        average: '22',
        fuel: 'Petrol',
        price: '500',
        availability: 'true',
        owner: 'PradipRaj Vala',
    },
]

export default cars;